import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {webkit}=require('/tmp/niko2-browser-qa/node_modules/playwright');
const cfg=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const target=cfg.target;
if(new URL(target).origin!=='https://niko2-atelier-combined-preview.25mochiko25.workers.dev')throw Error('Unexpected target');
const out='qa-output/mobile-follow';fs.mkdirSync(out,{recursive:true});
const report={target,persona:'sloppy-mobile',method:'Focused additional fresh WebKit session for perfume, Diary and Cabinet after the preceding interior session. Visible UI only. No product source, storage injection, hash jumps or private app calls. ScrollIntoView/programmatic scrolling is not finger inertia.',startedAt:new Date().toISOString(),engine:'WebKit',viewport:[390,844],events:[],observations:[],limits:[],pageErrors:[],httpErrors:[]};
const b=await webkit.launch({headless:true});const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,locale:'ja-JP',timezoneId:'Asia/Tokyo'});const p=await c.newPage();p.setDefaultTimeout(4000);p.setDefaultNavigationTimeout(18000);
p.on('pageerror',e=>report.pageErrors.push(String(e)));p.on('response',r=>{if(r.status()>=400){const u=new URL(r.url());report.httpErrors.push({path:u.origin+u.pathname,status:r.status()});}});
const pause=ms=>p.waitForTimeout(ms);const route=()=>p.locator('.view.is-active').getAttribute('data-view').catch(()=>null);let imageNo=0,actionNo=0;const deadline=Date.now()+180000;
function flush(){fs.writeFileSync(path.join(out,'observations.json'),JSON.stringify(report,null,2));}
async function snap(label,image=false){const s=await p.evaluate(()=>{
 function vis(e){if(!e||e.closest('[hidden],[inert]'))return false;const r=e.getBoundingClientRect();if(r.width<1||r.height<1)return false;for(let n=e;n&&n.nodeType===1;n=n.parentElement){const q=getComputedStyle(n);if(q.display==='none'||q.visibility==='hidden'||Number(q.opacity)===0)return false;}return true;}
 const overlays=[...document.querySelectorAll('dialog[open],#niko2FirstDreamIntro,#niko2FirstGardenResponse,.niko2-post-garden')].filter(vis),root=overlays.at(-1)||document.querySelector('.view.is-active')||document.body;
 return{url:location.origin+location.pathname+location.hash,route:document.querySelector('.view.is-active')?.dataset.view,activeViews:document.querySelectorAll('.view.is-active').length,text:(root.innerText||'').trim().replace(/\s+/g,' ').slice(0,7500),overlays:overlays.map(e=>e.id||e.className),scroll:[scrollX,scrollY,document.documentElement.scrollWidth,document.documentElement.scrollHeight],overflow:document.documentElement.scrollWidth>innerWidth+2,controls:[...root.querySelectorAll('button,a,summary')].filter(vis).map(e=>{const r=e.getBoundingClientRect(),x=Math.max(0,Math.min(innerWidth-1,r.x+r.width/2)),y=Math.max(0,Math.min(innerHeight-1,r.y+r.height/2)),hit=document.elementFromPoint(x,y);return{id:e.id,text:(e.innerText||e.getAttribute('aria-label')||e.getAttribute('title')||'').trim().replace(/\s+/g,' ').slice(0,120),disabled:!!e.disabled,rect:[Math.round(r.x),Math.round(r.y),Math.round(r.width),Math.round(r.height)],onscreen:r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth,hit:!!hit&&(hit===e||e.contains(hit)),href:e.getAttribute('href')};}).slice(0,120),images:[...root.querySelectorAll('img')].filter(vis).slice(0,15).map(e=>({alt:e.alt,loaded:e.complete&&e.naturalWidth>0})),entries:[...document.querySelectorAll('.diary-recent-piece,.diary-entry')].filter(vis).map(e=>({text:(e.innerText||'').trim().slice(0,250),label:e.getAttribute('aria-label')}))};}).catch(e=>({error:String(e)}));const row={label,at:new Date().toISOString(),...s};if(image&&imageNo<12){row.image=String(++imageNo).padStart(2,'0')+'-'+label.replace(/[^a-zA-Z0-9_-]/g,'_')+'.jpg';await p.screenshot({path:path.join(out,row.image),type:'jpeg',quality:70,timeout:7000}).catch(e=>row.imageError=String(e));}report.observations.push(row);flush();console.log('OBS '+JSON.stringify({label,route:s.route,text:s.text?.slice(0,100),image:row.image}));return row;}
async function act(label,fn,delay=350,image=false){if(Date.now()>deadline||actionNo++>85)throw Error('Bounded session budget reached');const before=await snap(label+':before');let error=null;const start=Date.now();try{await fn();}catch(e){error=String(e);report.limits.push({label,error});}await pause(delay);const after=await snap(label+':after',image);report.events.push({label,before:before.label,after:after.label,beforeRoute:before.route,afterRoute:after.route,elapsed:Date.now()-start,error});flush();return !error;}
async function first(sel){const all=p.locator(sel);for(let i=0;i<Math.min(await all.count(),30);i++){const e=all.nth(i);if(await e.isVisible().catch(()=>false)&&await e.isEnabled().catch(()=>true))return e;}return null;}
async function tap(sel,label,delay=350,image=false){const el=await first(sel);if(!el){report.limits.push({label,reason:'No visible enabled target'});return false;}return act(label,()=>el.tap(),delay,image);}
async function textButton(text){const all=p.locator('button:visible');for(let i=0;i<await all.count();i++){const el=all.nth(i);if((await el.innerText()).trim().replace(/\s+/g,' ')===text&&await el.isEnabled())return el;}return null;}
async function named(text,label,delay=180){const el=await textButton(text);if(!el){report.limits.push({label,reason:'Displayed text not found: '+text});return false;}return act(label,()=>el.tap(),delay);}
async function two(el,label){if(!el){report.limits.push({label,reason:'No target'});return false;}await el.scrollIntoViewIfNeeded();return act(label,async()=>{const r=await el.boundingBox();if(!r)throw Error('No box');const x=Math.max(1,Math.min(388,r.x+r.width/2)),y=Math.max(1,Math.min(842,r.y+r.height/2));const hits=[];for(let i=0;i<2;i++){hits.push(await p.evaluate(({x,y})=>{const e=document.elementFromPoint(x,y)?.closest('button,a,[role=button]');return e?{id:e.id,text:(e.innerText||e.getAttribute('aria-label')||'').slice(0,100)}:null;},{x,y}));await p.touchscreen.tap(x,y);if(!i)await pause(160);}report.events.push({label:label+':input-hits',kind:'two coordinate taps',gapMs:160,hits,x,y});},650);}
async function guides(){for(let i=0;i<8;i++){const l=await first('#niko2FirstDreamIntro .niko2-intro-primary,#niko2FirstGardenResponse .niko2-intro-primary,.niko2-post-garden .niko2-intro-primary');if(!l)return;const concept=await first('.niko2-intro-concept-button:visible');if(concept&&!await p.locator('.niko2-intro-concept-button.is-selected:visible').count())await act('select shown concept',()=>concept.tap(),160);if(!await act('guide '+await l.innerText(),()=>l.tap(),400))return;}}
async function skip(){for(let i=0;i<2;i++){if(!['garden','quiet'].includes(await route()))break;if(!await tap('#gardenSkipControl','known Garden exit '+i,750))break;}await guides();}
async function home(){const close=await first('#closeDiaryEntryDetail,dialog[open] button[aria-label*="閉"]');if(close)await act('close detail before return',()=>close.tap(),250);if(await route()==='home'){await guides();return true;}await tap('a[data-route="home"]:visible,button[data-route="home"]:visible,a[href="#home"]:visible','visible Home return',600);await guides();return await route()==='home';}
async function openDiary(){if(await route()==='diary')return true;if(!await home())return false;return tap('.home-diary-entry','open Diary by Home control',650);}
try{
 const res=await p.goto(target,{waitUntil:'domcontentloaded'});report.httpStatus=res?.status();await pause(900);await tap('#enterGarden','public entry',400);await guides();await skip();
 for(let n=0;n<5&&await route()!=='perfume';n++){if(!await home())break;await tap('#enterGarden','open offered dream '+n,850);if(['garden','quiet'].includes(await route()))await skip();}
 if(await route()!=='perfume')throw Error('Perfume was not offered via the bounded visible route');
 await tap('#enterPerfumeWorkbench','open workbench',450);await named('01 TOP','select TOP');
 await two(await textButton('雨'),'tap rain twice quickly');await named('02 MIDDLE','change to MIDDLE');await named('古いぬいぐるみ','put old plush in MIDDLE');await named('03 LAST','change to LAST');await named('燃えた砂糖','put burnt sugar in LAST');await snap('three-layers-before-compose',true);
 await act('scroll workbench toward bottom',()=>p.evaluate(()=>{let e=document.elementFromPoint(innerWidth/2,innerHeight*.7);for(;e&&e!==document.body;e=e.parentElement){if(e.scrollHeight>e.clientHeight+20&&/auto|scroll/.test(getComputedStyle(e).overflowY)){e.scrollBy({top:650,behavior:'auto'});return;}}window.scrollBy(0,650);}),100);
 await two(await first('#composePerfume'),'compose then tap again');await p.locator('#perfumeResult').waitFor({state:'visible',timeout:18000});await pause(1900);await snap('finished-perfume',true);
 await two(await first('#savePerfumeArtifact'),'save then tap again');await snap('diary-immediately-after-save',true);
 if(await route()!=='diary')throw Error('Saving did not lead to Diary');
 const entry=await first('.diary-recent-piece,.diary-entry');if(entry)await act('open newly saved perfume detail',()=>entry.tap(),500,true);await tap('#closeDiaryEntryDetail','close saved detail',180);
 await act('browser Back after saving',()=>p.goBack({waitUntil:'domcontentloaded',timeout:7000}),450);await act('browser Forward after saving',()=>p.goForward({waitUntil:'domcontentloaded',timeout:7000}),450);await snap('saved-history-return',true);
 await act('reload saved Diary',()=>p.reload({waitUntil:'domcontentloaded'}),800);await openDiary();await snap('diary-reopened-after-reload',true);
 const entry2=await first('.diary-recent-piece,.diary-entry');if(entry2)await act('open saved item again after reload',()=>entry2.tap(),450,true);const close=await first('#closeDiaryEntryDetail');if(close)await act('close persisted saved item',()=>close.tap(),180);
 const threshold=await first('#openCabinetThreshold');if(threshold){await act('scroll to Cabinet threshold',()=>threshold.scrollIntoViewIfNeeded(),150);await tap('#openCabinetThreshold','open Cabinet threshold',250,true);await tap('#enterCabinet','enter Cabinet',650,true);await act('Back from Cabinet',()=>p.goBack({waitUntil:'domcontentloaded',timeout:7000}),350);await act('Forward back into Cabinet',()=>p.goForward({waitUntil:'domcontentloaded',timeout:7000}),400);await snap('cabinet-after-history',true);}
 await snap('final');
}catch(e){report.fatal=String(e.stack||e);await snap('stopped',true).catch(()=>{});}finally{report.finishedAt=new Date().toISOString();flush();const lines=['# Focused saved-object mobile followthrough','Target: '+target,'Method: '+report.method,'Started: '+report.startedAt,'Finished: '+report.finishedAt,'',...report.events.map((e,i)=>`${i+1}. ${e.label} | ${e.beforeRoute||''} -> ${e.afterRoute||''} | ${e.error||'OK'}`),'','## Observations',...report.observations.flatMap(s=>['','### '+s.label+' / '+s.route,s.text||'','ENTRIES: '+JSON.stringify(s.entries||[]),'OVERLAYS: '+JSON.stringify(s.overlays||[]),'VISIBLE CONTROLS: '+(s.controls||[]).filter(x=>x.onscreen).map(x=>x.id+':'+x.text+(x.disabled?' [disabled]':'')+(!x.hit?' [covered]':'')).join(' | ')]),'','## Limits',JSON.stringify(report.limits,null,2),'## Page errors',JSON.stringify(report.pageErrors),'## HTTP errors',JSON.stringify(report.httpErrors),'## Fatal',report.fatal||'None'];fs.writeFileSync(path.join(out,'evidence.md'),lines.join('\n'));await c.close();await b.close();console.log('COMPLETE '+JSON.stringify({actions:actionNo,limits:report.limits.length,errors:report.pageErrors,fatal:report.fatal||null}));}
